import { CircleAlertIcon } from "lucide-react"

import { ORGANIZATION_ASSIGNABLE_DESK_ITEMS } from "@/components/admin-osa/signatory-roles"
import {
  HigherCouncilField,
  SignatoryDeskCombobox,
} from "@/components/admin/organizations/organization-fields"
import { useOrganizationsPage } from "@/components/admin/organizations/organizations-context"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogPanel,
  DialogPopup,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Field,
  FieldDescription,
  FieldLabel,
} from "@/components/ui/field"
import { Form } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { modal } from "@/config"

export function EditOrganizationDialog() {
  const { state, actions } = useOrganizationsPage()

  return (
    <Dialog
      onOpenChange={(open) => {
        if (!open) actions.closeEdit()
      }}
      open={state.editing !== null}
    >
      <DialogPopup className={modal.dialogMd}>
        <DialogHeader>
          <DialogTitle>Edit organization</DialogTitle>
          <DialogDescription>
            The organization ID cannot be changed.
          </DialogDescription>
        </DialogHeader>
        <Form className="contents" onSubmit={actions.handleEditSave}>
          <DialogPanel className="flex flex-col gap-4">
            <Field>
              <FieldLabel htmlFor="edit-organization-id">Organization ID</FieldLabel>
              <Input
                disabled
                id="edit-organization-id"
                readOnly
                type="text"
                value={state.editing?.organization_id ?? ""}
              />
              <FieldDescription>Generated by the API.</FieldDescription>
            </Field>
            <Field>
              <FieldLabel htmlFor="edit-organization-name">Name</FieldLabel>
              <Input
                autoComplete="off"
                id="edit-organization-name"
                onChange={(event) =>
                  actions.changeEditName(event.currentTarget.value)
                }
                required
                type="text"
                value={state.editName}
              />
            </Field>
            {ORGANIZATION_ASSIGNABLE_DESK_ITEMS.map((item) => (
              <SignatoryDeskCombobox
                emptyLabel={`No ${item.label} registered`}
                items={state.deskOptions[item.value]}
                key={item.value}
                label={item.label}
                onValueChange={(value) => actions.changeEditDesk(item.value, value)}
                optionalLabel={
                  item.value === "dean" && state.editIsHigherCouncil
                    ? "Not required — higher councils skip the dean desk."
                    : undefined
                }
                placeholder={`Search ${item.label.toLowerCase()}`}
                value={state.editDesks[item.value]}
              />
            ))}
            <HigherCouncilField
              checked={state.editIsHigherCouncil}
              id="edit-organization-higher-council"
              onCheckedChange={actions.setEditIsHigherCouncil}
            />
            {state.editError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not save</AlertTitle>
                <AlertDescription>{state.editError}</AlertDescription>
              </Alert>
            ) : null}
            {state.deleteError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not delete</AlertTitle>
                <AlertDescription>{state.deleteError}</AlertDescription>
              </Alert>
            ) : null}
          </DialogPanel>
          <DialogFooter>
            <Button
              onClick={actions.openDelete}
              type="button"
              variant="destructive-outline"
            >
              Delete
            </Button>
            <DialogClose render={<Button type="button" variant="ghost" />}>
              Cancel
            </DialogClose>
            <Button loading={state.updatePending} type="submit">
              Save changes
            </Button>
          </DialogFooter>
        </Form>
      </DialogPopup>
    </Dialog>
  )
}
