import { CircleAlertIcon } from "lucide-react"

import { useCampusesPage } from "@/components/admin/campuses/campuses-context"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogPanel,
  DialogPopup,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Field,
  FieldDescription,
  FieldLabel,
} from "@/components/ui/field"
import { Form } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { modal } from "@/config"

export function EditCampusDialog() {
  const { state, actions } = useCampusesPage()

  return (
    <Dialog
      onOpenChange={(open) => {
        if (!open) actions.closeEdit()
      }}
      open={state.editing !== null}
    >
      <DialogPopup className={modal.dialogMd}>
        <DialogHeader>
          <DialogTitle>Edit campus</DialogTitle>
          <DialogDescription>The campus ID cannot be changed.</DialogDescription>
        </DialogHeader>
        <Form className="contents" onSubmit={actions.handleEditSave}>
          <DialogPanel className="flex flex-col gap-4">
            <Field>
              <FieldLabel htmlFor="edit-campus-id">Campus ID</FieldLabel>
              <Input
                disabled
                id="edit-campus-id"
                readOnly
                type="text"
                value={state.editing?.campus_id ?? ""}
              />
              <FieldDescription>Generated by the API.</FieldDescription>
            </Field>
            <Field>
              <FieldLabel htmlFor="edit-campus-name">Name</FieldLabel>
              <Input
                autoComplete="off"
                id="edit-campus-name"
                onChange={(event) =>
                  actions.changeEditName(event.currentTarget.value)
                }
                required
                type="text"
                value={state.editName}
              />
            </Field>
            {state.editError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not save</AlertTitle>
                <AlertDescription>{state.editError}</AlertDescription>
              </Alert>
            ) : null}
            {state.deleteError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not delete</AlertTitle>
                <AlertDescription>{state.deleteError}</AlertDescription>
              </Alert>
            ) : null}
          </DialogPanel>
          <DialogFooter>
            <Button
              onClick={actions.openDelete}
              type="button"
              variant="destructive-outline"
            >
              Delete
            </Button>
            <DialogClose render={<Button type="button" variant="ghost" />}>
              Cancel
            </DialogClose>
            <Button loading={state.updatePending} type="submit">
              Save changes
            </Button>
          </DialogFooter>
        </Form>
      </DialogPopup>
    </Dialog>
  )
}
