import { CircleAlertIcon } from "lucide-react"

import { DepartmentSelect } from "@/components/admin/signatories/department-select"
import { useSignatoriesPage } from "@/components/admin/signatories/signatories-context"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogPanel,
  DialogPopup,
  DialogTitle,
} from "@/components/ui/dialog"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { Form } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectItem,
  SelectPopup,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { modal } from "@/config"

export function EditSignatoryDialog() {
  const { state, actions } = useSignatoriesPage()

  return (
    <Dialog
      onOpenChange={(open) => {
        if (!open) actions.closeEdit()
      }}
      open={state.editing !== null}
    >
      <DialogPopup className={modal.dialogMd}>
        <DialogHeader>
          <DialogTitle>Edit signatory</DialogTitle>
          <DialogDescription>The signatory ID cannot be changed.</DialogDescription>
        </DialogHeader>
        <Form className="contents" onSubmit={actions.handleEditSave}>
          <DialogPanel className="flex flex-col gap-4">
            <Field>
              <FieldLabel htmlFor="edit-signatory-id">Signatory ID</FieldLabel>
              <Input
                disabled
                id="edit-signatory-id"
                readOnly
                type="text"
                value={state.editing?.signatory_id ?? ""}
              />
              <FieldDescription>Generated by the API.</FieldDescription>
            </Field>
            <Field>
              <FieldLabel htmlFor="edit-signatory-name">Name</FieldLabel>
              <Input
                autoComplete="off"
                id="edit-signatory-name"
                onChange={(event) =>
                  actions.changeEditName(event.currentTarget.value)
                }
                required
                type="text"
                value={state.editName}
              />
            </Field>
            <Field>
              <FieldLabel>Role</FieldLabel>
              <Select
                itemToStringValue={(item) => item.value}
                items={state.editRoleItems}
                onValueChange={(item) => actions.changeEditRole(item?.value ?? null)}
                value={state.selectedEditRole}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select role" />
                </SelectTrigger>
                <SelectPopup>
                  {state.editRoleItems.map((item) => (
                    <SelectItem key={item.value} value={item}>
                      {item.label}
                    </SelectItem>
                  ))}
                </SelectPopup>
              </Select>
            </Field>
            {state.editRole === "dean" ? (
              <DepartmentSelect
                items={state.editDepartmentItems}
                onValueChange={actions.setEditDepartment}
                value={state.editDepartment}
              />
            ) : null}
            {state.editError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not save</AlertTitle>
                <AlertDescription>{state.editError}</AlertDescription>
              </Alert>
            ) : null}
            {state.deleteError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not delete</AlertTitle>
                <AlertDescription>{state.deleteError}</AlertDescription>
              </Alert>
            ) : null}
          </DialogPanel>
          <DialogFooter>
            <Button
              onClick={actions.openDelete}
              type="button"
              variant="destructive-outline"
            >
              Delete
            </Button>
            <DialogClose render={<Button type="button" variant="ghost" />}>
              Cancel
            </DialogClose>
            <Button loading={state.updatePending} type="submit">
              Save changes
            </Button>
          </DialogFooter>
        </Form>
      </DialogPopup>
    </Dialog>
  )
}
